project:
  type: website
  output-dir: docs

website:
  title: "NRE Fall Seminar Series"
  navbar:
    right:
      - text: "NRE 692 Syllabus"
        file: 692_syllabus.pdf
      - text: "NRE 497 Syllabus"
        file: 497_syllabus.pdf
      - text: "Schedule"
        file: schedule.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false

editor: visual
