project:
  type: website

website:
  title: "NRE 692/492"
  navbar:
    right:
      - text: "692 Syllabus"
        file: 692_syllabus.pdf
      - text: "Schedule"
        file: schedule.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false

editor: visual

